// Database type will be regenerated by `supabase gen types typescript` in Week 1.
// Stub kept type-only so consumers can import { Database } today without runtime impact.
export type Database = Record<string, never>;
